run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code

    # Additional recommended linters
    - gofmt         # Check code is formatted
    - goimports     # Check imports are formatted
    - misspell      # Check for misspelled English words
    - revive        # Drop-in replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - gosec         # Security checks
    - gocritic      # Comprehensive Go source code linter
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code duplication detection
    - prealloc      # Find slice declarations that could be preallocated

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow  # Can be too strict

  gocyclo:
    min-complexity: 15  # Reasonable complexity threshold

  dupl:
    threshold: 100  # Lines to trigger duplication

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - whyNoLint  # Don't require explanation for nolint directives

  revive:
    rules:
      - name: exported
        disabled: true  # Don't require comments on all exported items yet
      - name: package-comments
        disabled: true  # Don't require package comments yet

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some common false positives
  exclude-rules:
    # Exclude all gosec warnings for test files (temporary test data)
    - path: _test\.go
      linters:
        - gosec

    # Exclude duplication warnings for test files
    - path: _test\.go
      linters:
        - dupl

    # Exclude octalLiteral warnings for test files
    - path: _test\.go
      linters:
        - gocritic
      text: "octalLiteral:"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
